language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo apt-get install oracle-java8-set-default -y


matrix:
    allow_failures:
        - php: hhvm

before_script: ./.ci/before_script.sh
script: "vendor/bin/phpunit Tests"
