language: php
php:
  - 5.6
  - 7
  - hhvm

addons:
  apt:
    packages:
      - oracle-java8-installer

matrix:
    allow_failures:
        - php: hhvm

before_script: ./.ci/before_script.sh
script: "vendor/bin/phpunit Tests"
